feedback reviews
PeaksoftFrontend/Gadgetarium-JS-Moscow pull request #16
Opened 2024-04-02 12:01 UTC by Aiposha

2024-04-03 17:34 UTC, AziatAbd requested changes

2024-04-03 17:34 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +   const [value, setValue] = useState(4);
value, currentValue'нун ичиннен келиш керек

2024-04-03 17:34 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +                  <h5></h5>
удалите

2024-04-03 17:34 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +                  <h3>{review.massage}</h3>
![image](https://github.com/PeaksoftFrontend/Gadgetarium-JS-Moscow/assets/115453436/d2c745c6-663c-4867-9efb-4f77e2617647)

как я могу увидеть ответ от представителя?

2024-04-03 17:34 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +                     <StyledRating name="read-only" value={value} />
добавьте атрибут readOnly

2024-04-03 17:34 UTC, AziatAbd commented on src/components/UI/ReviewsPagination.jsx
просто pagination

2024-04-03 17:34 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +                  <p>{review.time}</p>
![image](https://github.com/PeaksoftFrontend/Gadgetarium-JS-Moscow/assets/115453436/3e91701d-369c-44b0-9c71-6e05cf201258)

сделайте стили как на фигме

2024-04-03 17:34 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +               <img src={review.img} alt="#" />
img'тин ордуна MUI'дан Avatar деген компонента колдонсонуз

2024-04-05 15:09 UTC, AziatAbd commented
![image](https://github.com/PeaksoftFrontend/Gadgetarium-JS-Moscow/assets/115453436/f4784d4b-6d1f-4ac1-8d9e-f783eaa93bb4)
это инпут

2024-04-05 15:13 UTC, Aiposha commented
Нет инпут болуш керекби?

Пт, 5 апр. 2024 г. в 18:09, Aziat ***@***.***>:

> image.png (view on web)
> <https://github.com/PeaksoftFrontend/Gadgetarium-JS-Moscow/assets/115453436/f4784d4b-6d1f-4ac1-8d9e-f783eaa93bb4>
> это инпут
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PeaksoftFrontend/Gadgetarium-JS-Moscow/pull/16#issuecomment-2040048416>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BE5XFMV3XZEHLO2RTAXSLSDY325DNAVCNFSM6AAAAABFTH2KN6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBQGA2DQNBRGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-05 15:16 UTC, AziatAbd requested changes

2024-04-05 15:16 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +               <ModalButtun>Отменить</ModalButtun>
закройте модалку если нажать на отменить

2024-04-05 15:16 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +                     Спасибо, что выбираете нас. Хорошего дня!
если нажать на ответить то должна выходить модалка с пустым инпутом

2024-04-05 15:16 UTC, AziatAbd commented on src/components/UI/AdminReviews.jsx
> +                     Спасибо, что выбираете нас. Хорошего дня!
если нажать на редактировать то должен быть текст который написал админ

2024-04-05 15:19 UTC, AziatAbd requested changes

2024-04-05 15:19 UTC, AziatAbd commented on src/App.jsx
> +         <AdminReviews />
удалите

2024-04-07 14:57 UTC, merged