addButtonUI
PeaksoftFrontend/Gadgetarium-JS-Moscow pull request #5
Opened 2024-03-26 17:09 UTC by Maksat2222

2024-03-27 10:28 UTC, Maksat2222 commented
там я забыл в button.jsx  ненужный обект убрать и ширины а css простите

2024-03-29 17:01 UTC, AziatAbd requested changes

2024-03-29 17:01 UTC, AziatAbd commented on src/components/UI/Button.jsx
> +   width: '400px',
сделайте width: 100%. Не давайте фиксированные размеры

2024-03-29 17:01 UTC, AziatAbd commented on src/components/UI/Button.jsx
> +};
удалите, если не используете

2024-04-01 16:40 UTC, merged